Messages:
  Title: "<b><gradient:#FFE259:#F17700>ǫᴜᴇsᴛ</gradient><gradient:#F17700:#F17700>s</gradient></b>"
  Plugin_Prefix: "<gradient:#F2C641:#F29A2E>[Simp</gradient><gradient:#F29A2E:#D9753B>leQu</gradient><gradient:#D9753B:#D9653B>ests]</gradient>"
  Bottom_Message: "<gradient:#3494E6:#EC6EAD>ᴇxᴀᴍᴘʟᴇsᴇʀᴠᴇʀ.ɴᴇᴛ</gradient>"