name: ${name}
version: '${version}'
main: me.duart.scoreBoardQuests.ScoreBoardQuests
description: ${description}
api-version: '${apiVersion}'
authors: [ DaveDuart ]

dependencies:
  server:
    Vault:
      looad: BEFORE
      required: true