name: ScoreBoardQuests
version: '0.0.1'
main: me.duart.scoreBoardQuests.ScoreBoardQuests
api-version: '1.21'
authors: [ DaveDuart ]

depend: [ Vault ]

commands:
  sbquests:
    description: ScoreboardQuests commands
    aliases: [ sbq ]
    permission: scoreboardquests.admin
    permission-message: You do not have permission to use this command.